export function Data() {
  const data = {
    "The Shawshank Redemption": {
      title: "The Shawshank Redemption",
      review: `Whenever I talk about this movie with my friends, I do not even refer to it by title, but rather as "The Movie". When I say "The Movie", my friends know exactly what I'm talking about. In fact the main reason that me and my friends don't refer to it by title is because this movie is so great, that we do not feel worthy enough to say it's name in vain! I still remember the first time I saw The Shawshank Redemption. Some friends of mine and I went to see it at one of those "Budget Theaters" over the summer of 1995. None of us really knew anything about the movie, but we had heard that it was pretty good. So, not having any real expectations, we saw it. When the final credits rolled and the lights came on in the theater, all of us just sat there with our jaws hanging down on the floor. I turned my head towards my friend Bob and said "That was the greatest movie I have ever seen in my entire life!" There's really no other way I can put it in words. Every moment of this movie captivated me and inspired me to believe in the one true thing in life...... "HOPE". This movie is sad, uplifting, inspiring, harsh, cold, funny (at the right times), jaw-dropping, and heart-warming all at the same time. I get chills every time I watch this film and this film contains the greatest ending (which takes place over the last 30 minutes or so)in movie history! How it all just "comes together" is so incredible and uplifting. I should also mention the music in this movie is nearly flawless as well, and the soundtrack is a "must buy" for any music fan. The only bad thing about this movie is the fact that I know I will never see a better movie, no matter how many I may see. I've seen many movies over the past few years, many excellent films. However, every time I walk out of the theater, I turn to my friend or family member that I saw it with and I say, "That was a great movie, but it wasn't nearly as good as 'you know what'!" There have been many movies over the past few years that thought would really move me or that I might one day call my "favorite of all time", but they've all fallen far short of "The Shawshank Redemption". So, if you have yet to see this movie, please run to the video store immediately. You're guaranteed to find it in the "employee picks" section. And if it isn't in that section, then you should tell the employees there that there is something seriously wrong with them. If you have seen this movie, go see it again. If you haven't bought your own copy yet, buy one. In fact buy two, and put one in a fire-proof safe, just in case of an emergency. :o) So, you want a 1-10 rating??? I give it a 13!!!!!!`,
    },
  };
  return data;
}
